### ISSUE TITLE
Trying to follow your tutorial but it appears out of date??

### ISSUE THREAD

**Issue by mbalsam-refind** [sveronneau/gcp#2]
I'm trying to follow this tutorial 

https://www.cloudops.com/blog/how-to-deploy-consul-in-gcp-using-terraform-your-first-step-towards-devops-automation/

that references this code.  But it appears out of date. 

So far the bugs appear to be 
- ${var.xxxx} ->  var.xxxx
- consult.tf - command = "sleep ....  master.yml -> ./gcp/consul/master.yml

Question: 
Is there an updated version of this tutorial?   Or a better one? 

If not, I can feed you the bugs? if you can help me fix them?

Best 
Mitchell

**Comment by sveronneau-slalom** [comment]
Hi Mitchell, this repo is 3 years old, wild old Consul, latest is 1.9.4, old terraform code.  

Hashicorp as a Consul 101 at https://learn.hashicorp.com/tutorials/consul/get-started-install

The Hashicorp registry site as a up to date example of Consul on GCP.

https://registry.terraform.io/modules/hashicorp/consul/google/latest

Hope it helps you out.

/Stacy

**Comment by mbalsam-refind** [comment]
Thanks!
